### PR TITLE
Add extraction of compressed wrap files

### PR DESCRIPTION
**Pull request by EladNLG**
it works, but it feels wrong(?)

am i supposed to `delete` the buffers after im done with them? doing so causes a crash, but if i don't it doesn't seem to cause a memory leak by looking at the debug menu?

CPP is weird.

### CODE REVIEW

**Comment by biast12** [comment]
it's not done yet

**Comment by biast12** [comment]
this pr works for me, tho idk if it's on purpose but there's still some old VPK files that's not in the wrapped format, they may just have been fully removed, but i do think it's worth a look in case it may not be

image

**Comment by EladNLG** [comment]
I don't think localization has been removed as a feature... I think we need to take a better look, maybe they've been moved to another file type (Datatable/RSON/something new?)

**Comment by biast12** [comment]
the thing is i looped through all the files with batch, so i can't missed any file, weird that it didn't export them then

**Comment by EladNLG** [comment]
weird...

**Comment by EladNLG** [comment]
> just checked with the GUI, and the folders aren't on there either, i tried to search for the audio folder while loading all the .rpaks above and it's not there

looks like the MNBK file is in <game install location>/audio/ship/ now? dont know if it was always there...

**Comment by biast12** [comment]
yeah the audio has always been there, but i'm talking about the audio script file, same with the other scripts shown above, like `entity_category.rson` and `entitlements.rson`

**Comment by mrsteyk** [comment]
> am i supposed to `delete` the buffers after im done with them? doing so causes a crash, but if i don't it doesn't seem to cause a memory leak by looking at the debug menu?

Yes you are supposed to. Debug builds do a break because you are deleting the same memory twice.
Original `delete[]` happens here: https://github.com/r-ex/LegionPlus/blame/72bc27ff415c1c7d0884f112e5ae4b8707a70ad2/Legion/src/rtech.cpp#L2729
Blame @IcePixelx

**Comment by EladNLG** [comment]
Slight issue: there are still NUL characters (and sometimes some extra newlines) at the end of files for some reason

**Comment by snake-biscuits** [comment]
> Slight issue: there are still NUL characters (and sometimes some extra newlines) at the end of files for some reason

Could be something about how `.client` wraps files
`.bsp_lump.client` should all be `Header.dcmpSize` bytes long, according to the `.bsp`

I did notice that the way scripts are redacted has changed:
 * No more `#if SERVER` blocks
 * No more whitespace, redacted lines are just newlines

**Pull request merged**
